config/routes.rb
Rails.application.routes.draw do
    
  get 'posts/new'

  get 'posts/create'

  get 'posts/index'

  root 'index#new'

  get '/signin',    to: 'sessions#new'
  post '/signin',   to: 'sessions#create'
  delete 'signout', to: 'sessions#delete'
  resources :posts, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token
    has_many :posts
    before_save { email.downcase! }
    validates :name, presence: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 25 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    
    def User.digest(string)
        Digest::SHA1.hexdigest(string)
    end
    
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    
    def remember
       self.remember_token = User.new_token
       update_attribute(:remember_digest, User.digest(remember_token))
    end
    
    def forget
       update_attribute(:remember_digest, nil) 
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
    
  # Logs in given user
  def sign_in(user)
      session[:user_id] = user.id
  end
    
    
  # Remembers given user in persistent session
  def remember(user)
     user.remember
     cookies.permanent.signed[:user_id] = user.id
     cookies.permanent[:remember_token] = user.remember_token
  end
    
  # Returns current signed-in user
  def current_user
      if (user_id = session[:user_id])
         @current_user ||= User.find_by(id: user_id) 
      elsif (user_id = cookies.signed[:user_id])
         user = User.find_by(id: user_id)
         if user && user.authenticated?(:remember, cookies[:remember_token])
             sign_in user
             @current_user = user
         end
      end
  end
  
  # Returns true if the current user is the given user
  def current_user?(user)
      user == current_user
  end
    
  # End session and forget user
  def sign_out
      forget(current_user)
      session.delete(:user_id)
      @current_user = nil
  end
    
  # Delete cookies
  def forget(user)
      cookies.delete(:user_id)
      cookies.delete(:remember_token)
  end
    
  def signed_in?
     !current_user.nil? 
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def new
      render :new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :signed_in_user, only: [:new, :create]
    
  def new
      @post = Post.new
  end

  def create
      @post = Post.new(post_params)
      @post.user_id = current_user.id
      if @post.save
          redirect_to posts_path
      else
          render :new
      end
  end

  def index
      @posts = Post.all
  end
    
    private
    
  def post_params
     params.require(:post).permit(:title, :body) 
  end
    
   def signed_in_user
       unless signed_in?
           flash[:danger] = "You must be a member to post!"
           redirect_to signin_url
       end
   end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
  def new
  end
    
  def create
      @user = User.find_by(email: params[:session][:email])
      if @user && @user.authenticate(params[:session][:password])
          sign_in @user
          remember @user
          flash[:success] = "You're signed in!"
          redirect_to root_url
      else
          flash.now[:error] = "Invalid username/password. Try again."
          render 'new'
      end
  end
    
  def delete
     sign_out if signed_in?
     flash[:success] = "You're signed out!"
     redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/index/new.html.erb
<div class="center jumbotron">
<h1>Members Only</h1>
    

<%= link_to "Posts", posts_path %>
<%= link_to "New Post", new_post_path %> 

<div class="welcome">
<p>Welcome to the Members Only App. Sign in to post and see who posted what.</p>
</div>
    
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Members Only", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <% if current_user %>
              <li id="name">Welcome <%= current_user.name %></li>
              <li><%= link_to "(Sign out)", signout_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
            </ul>
          </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message | %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<h1>Secret Posts</h1>

<div class="row">
 <div class="col-md-6 col-md-offset-3">
<ul class="post">
<% @posts.each do |post| %>

<li>Title: <%= post.title %> <br>
 Body: <%= post.body %> <br>
    <% if current_user %>
Author: <%= post.user.name %>
    <% else %>
Author: Anonymous
</li>

    <% end %>

<% end %>
    
</ul>
</div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="row">
 <div class="col-md-6 col-md-offset-3">
    <%= form_for(@post) do |f| %>
     
     <%= f.label :title %>
     <%= f.text_field :title, class: 'form-control' %>
     
     <%= f.label :body %>
     <%= f.text_area :body, class: 'form-control' %>
     
     
     <%= f.submit "Post", class: "btn btn-primary" %>
     
     <% end %>
     
    </div>
</div>